//@version=6
indicator("DrawingBoxes", overlay = true, max_boxes_count = 500)

const string DEFAULT_TIMEFRAMES = "1\n2\n3\n4\n5\n10\n15\n30\n96\n144\n288\n1h\n2h\n4h\n6h\n8h\n12h\n23h\n1d\n2d\n3d\n4d\n5d\n6d\n8d\n9d\n10d\n11d\n12d\n13d\n1w\n2w\n3w\n4w\n1m\n2m\n3m\n6m\n12m"
const string GROUP_TIMEFRAMES = "Timeframes"
timeframesInput = input.text_area(DEFAULT_TIMEFRAMES, "Timeframes", "Any number of timeframes.\nNew timeframe in new line.\nDuplicate entries are ignored.\nInvalid timeframes are ignored.\n\nFormat:\n  x => x minutes\n  xh => x hours\n  xd => x days\n  xm => x months", group = GROUP_TIMEFRAMES) 
limitTfs = input.int(10, "Max number of extra TFs", minval=0, maxval=40, step=1, tooltip = "How many extra timeframes should be analyzed besides current one?", group = GROUP_TIMEFRAMES)

use3BarsFVGOnly = input.bool(true, "Use only 3 bars FVGs")
mitigationLevelLimit = input.float(50.0, "Mitigation limit [%]", minval = 0.01, maxval = 99.99, step = 0.01, tooltip = "Blocks mitigated over this limit are eliminated")
fvgOverlapTreshold = input.float(85.0, "FVG minimal overlap treshold", minval = 0, maxval = 100, step = 0.01)
hiddenDepth = input.int(0, "Hidden depth", minval=0, step=1)
startFromFirstFVG = input.bool(false, "Start drawing from first FVG")
clusterLabels = input.bool(true, "Cluster closest labels")
clusterMargin = input.float(0, "Cluster Margin", minval = -5, step = 0.001) / 100

const string GROUP_DISPLAY = "Display"
var color blockColor = input.color(color.rgb(255, 228, 191, 85), "Block color", group = GROUP_DISPLAY)
var color blockBorderColor = input.color(color.rgb(118, 116, 116, 100), "Block border color", group = GROUP_DISPLAY)

dbgMode = input.bool(false, "Debug Mode")

type Block
    int left
    float top
    int right
    float bottom
    float drawTop
    float drawBottom
    float originalHeight
    float currentHeight
    float middlePoint
    float mitigationLevel
    int[] fvgs
    bool skipped
    string labelText
    box boxId

type Blocks
    Block[] active
    Block[] mitigated

type Timeframe
    string string
    string label
    int seconds
    bool isCurrent
    Blocks blocks

type Cluster
    float top
    float bottom
    Block[] blocks

var int chartTfInSeconds = timeframe.in_seconds()
var Timeframe[] timeframes = array.new<Timeframe>()

canUseTF(int tfInSeconds) =>
    bool result = true
    if tfInSeconds < chartTfInSeconds and chartTfInSeconds/tfInSeconds > 1000
        result := false
    result

init() =>
    map<string, Timeframe> uniqueTimeframes = map.new<string, Timeframe>()

    string chartTfLabel = switch
        (3600 <= chartTfInSeconds 
            and chartTfInSeconds <= 82800 
            and chartTfInSeconds % 3600 == 0) => str.format("{0}H", chartTfInSeconds / 3600)
        => timeframe.main_period

    uniqueTimeframes.put(chartTfLabel, Timeframe.new(
        string = timeframe.main_period,
        label = chartTfLabel,
        seconds = chartTfInSeconds,
        isCurrent = true,
        blocks = Blocks.new(
            active = array.new<Block>(),
            mitigated = array.new<Block>()
        )
    ))

    for userTf in str.split(str.upper(timeframesInput), "\n")
        string tf = str.trim(userTf)
        if uniqueTimeframes.contains(tf)
            continue // ignore duplicate entries
    
        string validTf = str.match(tf, "^((\\d+[SHDWM])|(\\d+))$")
        if validTf != ""
            if str.match(tf, "^\\d+H$") != ""
                h = str.tonumber(str.split(tf, "H").first())
                if h > 23 
                    continue // early exit
                // 1h -> 60, 2h -> 120, 3h -> 180 etc.
                validTf := str.tostring(h*60)

            int tfInSeconds = timeframe.in_seconds(validTf)
            uniqueTimeframes.put(tf, Timeframe.new(
                string = validTf,
                label = tf,
                seconds = tfInSeconds,
                isCurrent = false,
                blocks = Blocks.new(
                    active = array.new<Block>(),
                    mitigated = array.new<Block>()
                )
            ))

    Timeframe[] allTimeframes = uniqueTimeframes.values()
    allTimeframes.sort(order.ascending, "seconds")
    
    int currentTfIdx = -1
    for [i, tf] in allTimeframes
        if tf.isCurrent
            currentTfIdx := i
            break

    int timeframesCount = allTimeframes.size()-1
    int tfIdxLowerBound = math.max(0, math.min(currentTfIdx - int(limitTfs/2), timeframesCount - limitTfs))
    int tfIdxUpperBound = math.min(tfIdxLowerBound + limitTfs, timeframesCount)
    
    for i = tfIdxLowerBound to tfIdxUpperBound
        tf = allTimeframes.get(i)
        if canUseTF(tf.seconds)
            timeframes.push(tf)
    
innerLogic(Blocks blocks) =>
    float top1 = math.max(open[1], close[1])
    float top0 = math.max(open[0], close[0])
    float bottom1 = math.min(open[1], close[1])
    float bottom0 = math.min(open[0], close[0])

    changed = false

    for [i, block] in blocks.active
        if mitigationLevelLimit <= block.mitigationLevel
            blocks.active.remove(i)
            if not na(block.boxId)
                blocks.mitigated.push(block)
                changed := true
            continue

        if block.left < time[1]
            if block.skipped
                block.skipped := false
                if use3BarsFVGOnly
                    bool fvgBull = low > high[2]
                    bool fvgBear = high < low[2]

                    if (fvgBear or fvgBull)
                        float fvgTop = fvgBull ? low : fvgBear ? low[2] : na
                        float fvgBottom = fvgBull ? high[2] : fvgBear ? high : na
                        fvgOverlap = math.max(0, math.min(block.drawTop, fvgTop) - math.max(block.drawBottom, fvgBottom)) / block.currentHeight * 100
                        if fvgOverlap < fvgOverlapTreshold
                            blocks.active.remove(i)
                            changed := true
                            if not na(block.boxId)
                                blocks.mitigated.push(block)
                            continue
                    else
                        blocks.active.remove(i)
                        changed := true
                        if not na(block.boxId)
                            blocks.mitigated.push(block)
                        continue


            if block.drawBottom < high and low < block.drawTop
                float overlap = math.max(0, math.min(block.drawTop, high) - math.max(block.drawBottom, low)) / block.currentHeight * 100

                if (100 - mitigationLevelLimit) < overlap
                    float bodyOverlap = math.max(0, math.min(block.drawTop, top0)-math.max(block.drawBottom, bottom0)) / block.currentHeight * 100
                    if bodyOverlap > fvgOverlapTreshold
                        changed := true
                        block.skipped := true
                        if (block.fvgs.size() > 0 and block.fvgs.last() < time[0]) or block.fvgs.size() == 0
                            block.fvgs.push(time[0])
                        continue

                if overlap > 0 
                    if block.drawTop <= high
                        block.drawTop := low
                            
                    if low <= block.drawBottom
                        block.drawBottom := high

                    changed := true
                    if block.drawBottom < block.drawTop
                        block.currentHeight := block.drawTop - block.drawBottom
                        block.mitigationLevel := (1 - (block.currentHeight / block.originalHeight)) * 100
                        block.middlePoint := block.drawBottom + block.currentHeight / 2
                    else
                        blocks.active.remove(i)
                        if not na(block.boxId)
                            blocks.mitigated.push(block)


    bool diff = (open[1] != close[1] and open[0] != close[0]) and ((open[0] < close[0]) != (open[1] < close[1]))
    if diff    
        float top = math.min(top1, top0)
        float bottom = math.max(bottom1, bottom0)
        float height = top - bottom    

        if blocks.active.size() > 0
            Block prevBlock = blocks.active.last()
            if prevBlock.left == time[2]
                float overlap = math.max(0, math.min(prevBlock.drawTop, top)-math.max(prevBlock.drawBottom, bottom)) / prevBlock.currentHeight
                // if previous block overlaps with the new one - remove previous one
                if overlap > 0.95   
                    blocks.active.pop() 
                    if not na(prevBlock.boxId)
                        blocks.mitigated.push(prevBlock)

        Block newBlock = Block.new(
            left = time[1],
            top = top,
            right = time[0],
            bottom = bottom,
            drawTop = top,
            drawBottom = bottom,
            originalHeight = height,
            currentHeight = height,
            middlePoint = bottom + height / 2,
            mitigationLevel = 0.0,
            fvgs = array.new<int>(),
            skipped = false
        )
        
        changed := true
        blocks.active.push(newBlock)
        if blocks.active.size() > 100
            blocks.active.shift()

    changed


logic() => 
    var Blocks blocks = Blocks.new(
        active = array.new<Block>(),
        mitigated = array.new<Block>()
    )

    blocks.mitigated.clear()
    changed = innerLogic(blocks)

    if barstate.islast and changed
        blocks
    else
        na

merge_data(Blocks data, Block[] new_blocks) =>
    int i = 0
    int j = 0
    blocksCount = data.active.size()
    newBlocksCount = new_blocks.size()

    while i < blocksCount and j < newBlocksCount
        block = data.active.get(i)
        new_block = new_blocks.get(j)

        if block.left == new_block.left
            i += 1
            j += 1

            boxId = block.boxId
            block := new_block.copy()
            block.boxId := boxId
        else if block.left < new_block.left
            block.mitigationLevel := 100
            i += 1
        else
            data.active.push(new_block.copy())
            j += 1

    while i < data.active.size()
        block = data.active.get(i)
        block.mitigationLevel := 100
        i += 1

    while j < new_blocks.size()
        new_block = new_blocks.get(j)
        data.active.push(new_block.copy())
        j += 1

    data.active.sort(order.ascending, "left")
    if data.active.size() > 0
        for k = data.active.size() - 1 to 0
            block = data.active.get(k)
            if block.mitigationLevel > mitigationLevelLimit
                data.active.remove(k)
                if not na(block.boxId)
                    data.mitigated.push(block)

    
for tf in timeframes
    if tf.isCurrent
        innerLogic(tf.blocks)
    else
        blocks = request.security(
            symbol = syminfo.tickerid,
            timeframe = tf.string,
            expression = logic(),
            gaps = barmerge.gaps_off,
            lookahead = barmerge.lookahead_off,
            ignore_invalid_symbol = true
        )
        if not na(blocks)
            merge_data(tf.blocks, blocks.active)


    for block in tf.blocks.mitigated
        block.boxId.delete()
    tf.blocks.mitigated.clear()


if barstate.isfirst
    init()




if barstate.islast
    right = time + timeframe.in_seconds() * 10 * 1000

    for tf in timeframes
        for block in tf.blocks.active
            if hiddenDepth <= block.fvgs.size()
                block.labelText := str.format("{0}{1}", tf.label, block.fvgs.size() > 0 ? str.format(" x{0}", + block.fvgs.size()) : "")
                if na(block.boxId)
                    block.boxId := box.new(
                        left = (startFromFirstFVG and block.fvgs.size() > 0) ? block.fvgs.first() : block.left,
                        top = block.drawTop,
                        right = right,
                        bottom = block.drawBottom,
                        xloc = xloc.bar_time,
                        bgcolor = blockColor,
                        border_color = blockBorderColor,
                        text_color = color.white,
                        text_size = size.tiny,
                        text_valign = text.align_center,
                        text_halign = text.align_center,
                        text_font_family = font.family_monospace
                        // text = block.labelText
                    )
                else
                    block.boxId.set_top(block.drawTop)
                    block.boxId.set_bottom(block.drawBottom)
                    block.boxId.set_right(right)

    if clusterLabels
        tmpTimeframes = timeframes.copy()
        tmpTimeframes.sort(order.descending, "seconds")
        clusters = array.new<Cluster>()
        for tf in tmpTimeframes
            for block in tf.blocks.active
                if na(block.boxId)
                    continue

                Cluster matchingCluster = na
                for cluster in clusters
                    float overlap = math.max(0, math.min(block.drawTop, cluster.top) - math.max(block.drawBottom, cluster.bottom)) / (cluster.top - cluster.bottom)
                    if overlap > 0.1
                        matchingCluster:=cluster
                        break
                
                if na(matchingCluster)
                    matchingCluster:= Cluster.new(
                        top = block.drawTop,
                        bottom = block.drawBottom,
                        blocks = array.new<Block>()
                    )
                    clusters.push(matchingCluster)

                matchingCluster.blocks.push(block)
                matchingCluster.top := math.max(matchingCluster.top, block.drawTop) * (1+clusterMargin)
                matchingCluster.bottom := math.min(matchingCluster.bottom, block.drawBottom) * (1-clusterMargin)

        for cluster in clusters 
            lbls = array.new<string>()
            for block in cluster.blocks
                if lbls.size() > 0
                    if lbls.last() != block.labelText
                        lbls.push(block.labelText)
                    block.boxId.set_text("")
                else
                    lbls.push(block.labelText)

            cluster.blocks.sort(order.descending, "currentHeight")
            clusterBoxId = cluster.blocks.first().boxId
            clusterBoxId.set_text(lbls.join(" │ "))
            clusterBoxId.set_text_halign(text.align_center)

        if dbgMode
            log.info("\nClusters: {0}, Blocks: {1}", clusters.size(), box.all.size())

    else
        for tf in timeframes
            for block in tf.blocks.active
                if not na(block.boxId)
                    block.boxId.set_text(block.labelText)
